### ISSUE TITLE
USER STORY: View All User Messages

### ISSUE THREAD

**Issue by Vasileios20** [Vasileios20/real-estate#14]
As an **admin** I can **view all user messages in a page** so that I can **have a list with all the messages**

## Acceptance Criteria:
- The messages page displays a list of user messages.
- Admins can click on messages to view details.

## Tasks:
- [x] Design a messages page for viewing user messages.
- [x] Develop backend logic to retrieve and display user messages.
- [x] Implement frontend interaction for admins to click on messages and view details.
