### ISSUE TITLE
USER STORY: Update password

### ISSUE THREAD

**Issue by Vasileios20** [Vasileios20/real-estate#20]
As a **logged in user** I can **update my password** so that I can **change keep my profile secure**

## Acceptance Criteria:
- As a logged-in user, I should have access to a dedicated "Change Password" page.
- The "Change Password" page should include fields for updating the password and comfirm password.
- Users should have the option to cancel editing on the "Change Password" page, reverting to the original password, without saving changes.
## Tasks:
- [x] Design and implement a dedicated "Change Password" page accessible for logged-in users.
- [x] Define the fields for new and confirm password on the "Change Password" page.
- [x] Design and implement a "Save" button on the "Change Password" page.
- [x] Provide a "Cancel" button that allows users to exit the editing mode on the "Change Password" page without saving changes.
